"""
State definition for the Refactoring Swarm.
This state flows between all agents in the graph.
"""
from typing import TypedDict, List, Optional

class SwarmState(TypedDict):
    """
    The shared state passed between agents.
    
    Attributes:
        target_dir: Directory containing code to refactor
        files: List of Python files to process
        current_file: File currently being processed
        original_code: Original source code
        audit_report: Issues found by the Auditor
        refactoring_plan: Plan generated by the Auditor
        fixed_code: Code after Fixer applies corrections
        test_results: Output from pytest
        test_passed: Boolean indicating if tests passed
        error_logs: Error messages for retry attempts
        retry_count: Number of fix attempts for current file
        max_retries: Maximum retry attempts allowed
        completed_files: Files successfully processed
        failed_files: Files that failed after max retries
        messages: Conversation history for context
    """
    target_dir: str
    files: List[str]
    current_file: Optional[str]
    original_code: Optional[str]
    audit_report: Optional[str]
    refactoring_plan: Optional[str]
    fixed_code: Optional[str]
    test_results: Optional[str]
    test_passed: bool
    error_logs: Optional[str]
    retry_count: int
    max_retries: int
    completed_files: List[str]
    failed_files: List[str]
    messages: List[dict]
